name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Create static deployment structure
        run: |
          # Create .nojekyll file to bypass Jekyll processing
          touch .nojekyll
          
          # Create optimized deployment structure
          mkdir -p build
          cp -r public/* build/
          cp .nojekyll build/
          cp index.html build/
          cp CNAME build/
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: gh-pages
          clean: true
