name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, bcmath
          
      - name: Install Composer Dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction
      
      - name: Install NPM Dependencies
        run: npm ci
      
      - name: Build Assets
        run: npm run build
      
      - name: Configure .env
        run: |
          cp .env.example .env
          php artisan key:generate
          
      - name: Directory Permissions
        run: chmod -R 755 storage bootstrap/cache
      
      - name: Create optimized deployment structure
        run: |
          # Create .nojekyll file
          touch .nojekyll
          
          # Copy essential Laravel files for GitHub Pages
          mkdir -p deploy
          cp -r public/* deploy/
          cp .nojekyll deploy/
          cp index.html deploy/
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: deploy
          branch: gh-pages
          clean: true
